export const TYPES = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    ADD_QUESTIONS_ANSWERS: 'ADD_QUESTIONS_ANSWERS',
    ALL_QUESTIONS: 'ALL_QUESTIONS',
    MY_QUESTIONS: 'MY_QUESTIONS',
    MY_ANSWERS: 'MY_ANSWERS',
    NEW_QUESTION: 'NEW_QUESTION',
    NEW_ANSWER: 'NEW_ANSWER',
    UPDATE_QUESTION: 'UPDATE_QUESTION',
    DELETE_QUESTION: 'DELETE_QUESTION',
    UPDATE_ANSWER: 'UPDATE_ANSWER',
    DELETE_ANSWER: 'DELETE_ANSWER',
    UPDATE_USERNAME_DOB: 'UPDATE_USERNAME_DOB',
    UPDATE_EMAIL: 'UPDATE_EMAIL',
    UPDATE_PICTURE_URL: 'UPDATE_PICTURE_URL'
}